## init Homebrew / depends on architecture
if [ -f /usr/local/bin/brew ]; then
  eval "$(/usr/local/bin/brew shellenv)"
elif [ -f /opt/homebrew/bin/brew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

eval "$(starship init bash)"
eval "$(fzf --bash)"

## settings
export LANG=en_US.UTF-8
export AWS_CA_BUNDLE=$HOME/.aws/rootca.crt
export HOMEBREW_BUNDLE_FILE=~/.brewfile

## aliases
alias setup="ANSIBLE_LOCALHOST_WARNING="false" ANSIBLE_INVENTORY_UNPARSED_WARNING="false" ansible-playbook $HOME/.dotfiles/playbook.yaml"
alias k="kubectl"
alias kc="kubectx"
alias kn="kubens"
alias c="codium"