add_newline = false

[line_break]
disabled = true

[directory]
truncation_length = 8
style = 'cyan'
repo_root_style = 'green'

[git_branch]
style = 'purple'

[git_status]
style = 'red'

[helm]
disabled = true

[kubernetes]
disabled = false
format = '[$symbol$context]($style) in '
style = 'blue'